### ISSUE TITLE
Maven repo can't access 

### ISSUE THREAD

**Issue by SettingDust** [Hephaestus-Dev/FibLib#27]
https://hephaestus.dev/release/dev/hephaestus/FibLib/1.3.1+1.18.2/FibLib-1.3.1+1.18.2.pom is 404

**Comment by Draylar** [comment]
Hi, I ended up publishing FibLib to my own maven for projects due to this problem. If you're still interested in using FibLib, check out the 1.18.2 branch for my maven details. 

@Haven-King could I bother you to switch the default repository branch to 1.18.2, or give me permission to do it? Thanks so much <3!
